version: "3.9"
services:
  mysql:
    image: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: dcap
      MYSQL_DATABASE: dcap
      MYSQL_USER: dcap
      MYSQL_PASSWORD: dcap
    volumes:
      - "./dcap/dbSchema/dcapSchema.sql:/docker-entrypoint-initdb.d/1.sql"
    expose:
      - '3306'

  grafana:
    image: grafana/grafana-enterprise:latest
    ports:
      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=golioth-websocket-datasource
      - GF_PANELS_DISABLE_SANITIZE_HTML=TRUE

  dcap:
    build:
      context: './dcap'
      dockerfile: Dockerfile
    expose:
      - '8989'
    ports:
      - "8989:8989"
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - "mysql"

  nifi:
    build:
      context: './nifi'
      dockerfile: Dockerfile
    volumes:
      - "./nifi/templates/:/opt/nifi/nifi-1.13.0/conf/templates/"
      - "./nifi/processors/:/processors/"
    ports:
      - 1111:8080
      - 1112:1112
      - 1113:1113
      - 1114:1114
